stages:
  - install_dependencies
  - test
  - build
  - generate_docs

install_dependencies:
  stage: install_dependencies
  image: golang:1.21.5-alpine3.19
  script:
    - go mod download
  cache:
    key: ${CI_COMMIT_REF_SLUG}-deps
    paths:
      - ./go.mod
      - ./go.sum

test:
  stage: test
  image: golang:1.21.5-alpine3.19
  script:
    - go test ./...
  needs:
    - install_dependencies

build:
  stage: build
  image: golang:1.21.5-alpine3.19
  script:
    - go build -o server ./cmd/web/
  needs:
    - install_dependencies
    - test
  artifacts:
    paths:
      - ./server

generate_docs:
  stage: generate_docs
  image: golang:1.21.5-alpine3.19
  script:
    - go get -u golang.org/x/tools/cmd/godoc
    - godoc -http=:6060 & 
    - sleep 5
    - wget -qO- http://localhost:6060/pkg/ > docs.html
  artifacts:
    paths:
      - docs.html
  when: manual
    # - triggers