stages:
  - install_dependencies
  - test
  - build

install_dependencies:
  stage: install_dependencies
  image: golang:1.21.5-alpine3.19
  script:
    - go mod download
  cache:
    key: ${CI_COMMIT_REF_SLUG}-deps
    paths:
      - ./go.mod
      - ./go.sum

test:
  stage: test
  image: golang:1.21.5-alpine3.19
  script:
    - go test ./...
  dependencies:
    - install_dependencies

build:
  stage: build
  image: golang:1.21.5-alpine3.19
  script:
    - go build -o server ./cmd/web/
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - myapp
