stages:
  - install_dependencies
  - test
  - build
  - generate_docs

install_dependencies:
  stage: install_dependencies
  image: golang:1.21.5-alpine3.19
  script:
    - go mod download
  cache:
    key: ${CI_COMMIT_REF_SLUG}-deps
    paths:
      - ./go.mod
      - ./go.sum

test:
  stage: test
  image: golang:1.21.5-alpine3.19
  script:
    - go test ./...
  needs:
    - install_dependencies

build:
  stage: build
  image: golang:1.21.5-alpine3.19
  script:
    - go build -o server ./cmd/web/
  needs:
    - install_dependencies
    - test
  artifacts:
    paths:
      - ./server

generate_docs:
  stage: generate_docs
  image: golang:1.21.5-alpine3.19
  before_script:
    - go install golang.org/x/tools/cmd/godoc@latest
    - hostname=$(hostname)
    - echo "Hostname: $hostname"
  script:
    - godoc -http=:6060 &
    - sleep 5
    - wget -qO- "http://$hostname:6060/pkg/git.iu7.bmstu.ru/ka19iu10/Gtracker" > docs.html
  artifacts:
    paths:
      - docs.html